version: "3"
services:
  anvil:
    container_name: anvil
    hostname: anvil
    image: ghcr.io/foundry-rs/foundry:nightly
    ports:
      - "${PORT}:${PORT}"
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: wget http://${NODE_HOST}:${PORT}
      interval: 2s
      timeout: 5s
      retries: 30
    entrypoint:
      - anvil
      - --host=${NODE_HOST}
      - -m=${MNEMONIC}
      - -f=${FORKING_URL}
      - --fork-block-number=${FORKING_BLOCKNUMBER}
      - --fork-chain-id=${FORKING_NETWORK_ID}
